spring:
  application:
    name: spring-cloud-eureka

server:
  port: 8080

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: true
    fetch-registry: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
